{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"}"
    }
   ]
  },
  {
   "title": "upDownCounter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"Metrics\", __name__=\"upDownThingCount\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ObservableGauge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"Metrics\", __name__=\"observableGaugeCount\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "histogramCount_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ObservableUpDown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"Metrics\", __name__=\"observableUpDownCount\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "{job=\"Metrics\", __name__=\"greetings_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ObservableCounter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"Metrics\", __name__=\"observableCounterCount\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}