{
 "title": "Events warn",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Events information",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*Getting All Event.*\""
    }
   ]
  },
  {
   "title": "Tickets Information",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*Getting All Ticket.*\""
    }
   ]
  },
  {
   "title": "Events Error",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*Testing the eve.*\""
    }
   ]
  },
  {
   "title": "Tickets Error",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*Testing the ticket.*\""
    }
   ]
  },
  {
   "title": "Events Warn",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*Something about events.*\""
    }
   ]
  }
 ]
}